discordcr/discordcr

- src/discordcr/client.cr
- src/discordcr/mappings/gateway.cr
- src/discordcr/mappings/guild.cr
Previously, the gateway implementation was very basic, only supporting (apart from dispatches) `HELLO`, `IDENTIFY`, and heartbeats. Now it supports the entire protocol except for `HEARTBEAT_ACK`, which may be done in the future once the rest of the lib is tested stable.
> Full gateway implementation

- src/discordcr/mappings/channel.cr
- src/discordcr/mappings/converters.cr
- src/discordcr/mappings/gateway.cr
(I'm just assuming that discord uses the same formatting for time in the Gateway)
> Fix the format for converting discords Timestamps to Time

- src/discordcr/mappings/converters.cr
This was a breaking change in 0.20.4 that still needed to be handled.
> Fix the types of to_json arguments in converters

- README.md
Somebody complained about this and he has a point; we do have abstractions but they're pretty low level ones.
> Clarify the "no abstractions" thing in the readme

- src/discordcr/rest.cr
This wasn't possible to do before due to a lack of HTTP form data support in the stdlib.
> Add a REST method for uploading files

- src/discordcr/mappings/converters.cr
This fixes `#to_json` on any mapping that used these converters.
The converter's `#to_json` methods called `Builder#puts` - this method doesn't exist. I did some light digging, and I actually can't find where it came from.
> Fix #to_json in Converters

- examples/voice_send.cr
- src/discordcr/client.cr
- src/discordcr/dca.cr
- src/discordcr/mappings/vws.cr
- src/discordcr/sodium.cr
- src/discordcr/voice.cr
- src/discordcr/websocket.cr
This is a fully working implementation of voice sending to Discord. I have tested it and it worked without problems, however it would be useful if others would test this on their systems, given that it introduces a native dependency.
So far, only sending already-encoded Opus frames is supported, ~~and there is no automatic timing – the timing has to be done manually.~~ **(Automatic timing has been implemented)**
It should be used approximately like this **(Out of date, see the included example for a working demo)**:
```cr
client.voice_state_update(guild_id, channel_id, false, false)
client.on_voice_server_update do |payload|
voice_client = Discord::VoiceClient.new(payload, client.session, user_id)
voice_client.on_ready do
voice_client.send_speaking(true)
loop do
opus_data = …
```
> Basic voice sending

- src/discordcr/rest.cr
- The query endpoint no longer exists.
- The scope of this library is not aimed at user bots, so I'm not sure why the accept invite endpoint was included.
> Remove REST#query_users, REST#accept_invite

- src/discordcr/client.cr
- src/discordcr/mappings/gateway.cr
Apparently Discord is very specific about the `since` field: if it is 0 it is treated differently from being null, causing unpredictable behaviour. Now it is null by default. Fixes #71.
> Fix status updates being mostly broken

- deploy.sh
Tag builds should of course be tested and deployed rather than just tested. Previously this case was missed during checking whether the deployment should be skipped.
> Fix Travis tag builds being ignored for deployment

- src/discordcr/mappings/channel.cr
`reactions` was missing from the `Message` mapping.
This adds a data object for a `Reaction`, and makes `Message` parse any reactions on a message payload into an `Array(Reaction)`.
> add Reaction, Message#reactions

- src/discordcr/cache.cr
- src/discordcr/client.cr
- src/discordcr/mappings/gateway.cr
- src/discordcr/mappings/guild.cr
Fixes the two things mentioned in #60 — members and users from `GUILD_CREATE` not being cached, and missing getters for cache hashes. Also fixes a related bug uncovered during testing where nicks of cached members weren't updated properly.
> Member cache fixes, and getters for cache hashes

- src/discordcr/mappings/user.cr
Some fields which are only available for `/users/@me`. [Mostly taken from documentation](https://discordapp.com/developers/docs/resources/user#user-object-user-structure), the `phone` field found through messing around with Postman
> Add missing User fields

- src/discordcr/mappings/channel.cr
I went as best I could off of the talk / psuedocode in #35.
I didn't think it was really fitting to put it as a `self` method of `Discord` (`Discord.parse_mentions`) as `Message#content` is the only place they will ever occur.
I'm also not sure if [this is still desirable](https://github.com/meew0/discordcr/issues/35#issuecomment-254963274):
> [..] because you don't get their position in the string. 
I personally don't need it (did you mean the literal string index? and can't really think of a use case not covered by this PR, some kind of exotic parsing I guess?), but I can look into implementing it.
Also, not 100% sure how I feel about the overload `def parse_mentions(typ : MentionType)`.
Example usage: **(out of date, see diff)**
```crystal
msg = …
```
> Message#parse_mentions

- src/discordcr/mappings/user.cr
- src/discordcr/rest.cr
Icon is a nilable property - if a server has no icon, the value will be null.
This patch fixes that by setting `icon` as a nilable JSON property.
> Fixed exception in get_current_user_guilds

- src/discordcr/rest.cr
These methods would fail to compile with: "can't restrict Int32 to UInt32"
> Fix mismatches of default arguments type with their restrictions

- src/discordcr/mappings/channel.cr
[This field doesn't exist in API v6](https://discordapp.com/developers/docs/change-log#july-19-2017). DM channels are indicated by `type == 1` (DM) or `type == 3` (group DM).
> Remove Channel#is_private?

- src/discordcr/rest.cr
The number expected by Discord is `0-1000`. Also the default should be 1000, since most of the time one will want to get all members at once.
> fix type for list_guild_members

- spec/rest_spec.cr
- src/discordcr/rest.cr
This accomplishes the same (supersedes) as #80 , by making a single helper method that encodes tuples using `JSON.build` that skips null-valued keys for the same performance, as far as I can see.
While there's nothing wrong with additional structs in #80, if the *only* reason there are there is to control null-emission when building JSON, it is much less work to maintain the REST binding with this as you no longer have to maintain *both* the methods and the structs as API methods are added or fixed - you just call `encode_tuple` and don't have to think about anything else.
I originally wanted to make this a private method, as there's no real reason to expose it, but I'm not sure how I would spec the private method, as that doesn't compile.
This also does some small housekeeping of …
> Add helper method for encoding tuples to JSON, omitting pairs with null values

- spec/discordcr_spec.cr
- src/discordcr/mappings/channel.cr
- src/discordcr/mappings/converters.cr
- src/discordcr/mappings/gateway.cr
Discord sometimes sends timestamps without floating point accuracy, which is still a valid ISO 8601 timestamp. This would throw an exception and fail to parse the message.
> Use TimestampConverter instead of DATE_FORMAT

- src/discordcr/mappings/gateway.cr
- src/discordcr/mappings/guild.cr
- src/discordcr/rest.cr
A guild ban has two keys, `user` and `guild_id`.
> Fix GuildBan payload

- spec/discordcr_spec.cr
- src/discordcr/mappings/enums.cr
- src/discordcr/mappings/rest.cr
- src/discordcr/rest.cr
This endpoint doesn't work as written. I've renamed it to match the intended endpoint, and added a struct to pass as an argument.
It may be helpful to add an abstraction that lets you move channels around in the most basic manner, as [it's kind of a pain](https://github.com/z64/discordrb/blob/8972d84b222bcdcd027e4f81e8dd9e71a0e57aaa/lib/discordrb/data.rb#L1374-L1434). Would this be acceptable? If so I'll do this in another PR. This one at least makes the endpoint usable.
> Fix REST#modify_guild_channel_positions

- src/discordcr/mappings/rest.cr
- src/discordcr/rest.cr
- Use `encode_tuple` helper instead of structs (there was also two of the same exact struct..)
- Fix `modify_webhook_with_token` with wrong endpoint
- Fix `modify_webhook_with_token` accepting `channel_id` ("[..] does not accept a channel_id parameter in the body" from [docs](https://discordapp.com/developers/docs/resources/webhook#modify-webhook-with-token))
> Fix webhook related endpoints

- examples/mention_parser.cr
- spec/mention_spec.cr
- src/discordcr/mention.cr
Refactoring of #64 
I ended up liking this a lot better than imposing an API over `Message`, as there's times when your content may not be coming from Discord (database, cache). If we still want that (`Message#parse_mentions`) that is trivial to add.
From the feedback in #64, this has:
- Stronger typing; structs for each mention type instead of an enum, methods specific to each mention type.
- Each mention type has `#position` and `#size`
- A few specs
- Support for the new animated flag in custom emoji mentions
Notes:
- ~~I was unsure about the `#not_nil!` assertion on `Regex::MatchData#begin`, as I couldn't think of when in this implementation it would ever be nil.~~ N/A in parser refactor
- @RX14 , you had wanted `#user_mentions`, etc. - I missed this when I refactored it, but I …
> Add Mention.parse utility for parsing mentions

- src/discordcr/client.cr
At the moment there's no way to completely halt a running client. The websocket isn't exposed publicly, so you have to hack via `client.@websocket.close` or similar, but even then it will try to reconnect after `@backoff`.
> Add Client#stop

- spec/discordcr_spec.cr
- src/discordcr/mappings/channel.cr
- src/discordcr/mappings/converters.cr
- src/discordcr/rest.cr
Users should be able to work with these objects with the abstract enum values instead of having to look up a reference of what each integer value means.
> Use enums for Message and Channel type

- src/discordcr/mappings/rest.cr
- src/discordcr/rest.cr
Add `GET /gateway/bot` endpoint.
Note that without #124, setting up sharded clients will require doing heartbeat setup twice.
> Add get_gateway_bot

- src/discordcr/client.cr
This just came about because #129 was merged and then #126 was merged without being updated to use the lazy getter.
> Fix Client#stop

- spec/discordcr_spec.cr
- src/discordcr/mappings/channel.cr
- src/discordcr/mappings/converters.cr
- src/discordcr/mappings/guild.cr
- src/discordcr/mappings/invite.cr
- src/discordcr/voice.cr
Surpasses #114 (that change is actually wrong)
The location of timestamps is now parsed out of the format, specifying `Kind` (or its successor, `Location`) is not necessary.
Additionally, the formats between `TimestampConverter` and `EmbedTimestampConverter` were so similar and compatible, that I've removed it and use `TimestampConverter` everywhere.
I also do this because `Time::Format::ISO_8601_DATE`/`DATE_TIME` no longer defines `.from_json`/`.to_json`. 
I've tested this for a while on a live connection as well as some chat logs I had laying around on disk from previous issues with parsing timestamps with no issues.
> Changes for Crystal 0.25

- src/discordcr/rest.cr
The API returns `204 No Content` if the user is already a member of the guild. (This isn't documented in the API docs :disappointed: )
> Fix REST#add_guild_member when user is already a member

- src/discordcr/mappings/gateway.cr
- src/discordcr/rest.cr
- src/discordcr/snowflake.cr
Updated my main bot to v0.4 and got some leftover things from #130 (Sorry! :disappointed:)
Right now `Snowflake` doesn't interpolate into HTTP routes well, so using `Snowflakes` in `REST` fails. I've fixed this by `def to_s(io : IO)`, writing the internal `@value`.
```cr
s = Discord::Snowflake.new(123_u64)
puts "/some/#{s}/route" # => "/some/Discord::Snowflake(@value=123_u64)/route"
s = Discord::Snowflake.new(123_u64)
puts "/some/#{s}/route" # => "/some/123/route"
```
Workaround is to use, i.e., `message.channel_id.to_u64` (or patch this yourself)
Secondly, looks like I just missed the `?` in subbing out an `Array(UInt64)?` type restriction. I reviewed #130 again and it looks like this is the only one I missed.
> Fix Snowflake interpolation, mention_roles type

- spec/discordcr_spec.cr
- src/discordcr/mappings/channel.cr
- src/discordcr/mappings/converters.cr
Some more general cleanup. These aren't necessary as Crystal stdlib already handles JSON serde for `enum`.
The first commit removes the converters and fixes the specs. The second commit removes the specs, which I can drop if desired. Didn't see the point in keeping them around unless we are going to test all of our other types, but this is duplicating coverage we already get from the stdlib.
This also fixes some types not being able to be serialized because the converters didn't define `.to_json(value, builder)` (cc @velddev)
> Remove MessageTypeConverter, ChannelTypeConverter

- spec/snowflake_spec.cr
- src/discordcr/snowflake.cr
This makes Snowflake a little easier to work with for a common simple use case, comparing to a known literal value:
```cr
client.on_message_create do |payload|
next unless payload.author.id == 120571255635181568_u64
end
```
Currently you need to do `payload.author.id.to_u64`, etc.
> Snowflake is comparable to UInt64

- spec/cdn_spec.cr
- src/discordcr/cdn.cr
- src/discordcr/mappings/guild.cr
- src/discordcr/mappings/oauth2.cr
- src/discordcr/mappings/user.cr
Should `Discord::User#avatar_url`, etc be created that wraps these functions, or perhaps `CDN.user_avatar(user : User)`?
> Add utility methods for CDN resources

- src/discordcr/cache.cr
Introduced with change to Discord::Snowflake
(Actually I'm not sure whether it should be returning a UInt64 or Discord::Snowflake, but this is what I (was) expecting)
> Fix return type for Cache#resolve_dm_channel

- src/discordcr/mappings/channel.cr
Also changes `Voice` to `GuildVoice` per Discord's docs
> Add GuildCategory to ChannelType enum

- spec/paginator_spec.cr
- src/discordcr/paginator.cr
- src/discordcr/rest.cr
Implements a paginator utility class for making requests across paginated endpoints seamlessly.
This is useful for:
-  fetching large volumes of channel history for backfilling a chat log database 
- a means of examining all of the guilds a client is in if they're in more than 100
- listing all of the members of a guild if there are more than 1000
---
Example:
```cr
client.page_channel_messages(381889335278043137, limit: 20, page_size: 5).each do |message|
p({message.id.to_u64, message.author.username, message.content})
end
```
([Results](https://gist.github.com/z64/74413410bc11623d857e8aee191a5abc))
Closes #140
> Implement Discord::Paginator

- src/discordcr/paginator.cr
It seems like this caused docs to silently "fail"; hadn't noticed it as the docs tool was just keeping my old docs around I had already generated in previous commits.
> Fix docs generation

- spec/snowflake_spec.cr
- src/discordcr/snowflake.cr
The compliment to #147 , I wasn't sure that reopening `UInt64` for this was acceptable, but I think either way left & right hand comparison should work.
> UInt64 is comparable to Snowflake

- spec/voice_spec.cr
- src/discordcr/voice.cr
The voice structures are very simple and well defined; using an IO::Memory isn't necessary when we can simply write to a Slice.
Added tests for affected methods in VoiceUDP
Tests pass on current master: (barring the change to `getter socket` and making `create_header` `:nodoc:`)
```
$ git log -n 1 --oneline
27ba66ac (HEAD -> master, origin/master, origin/HEAD) UInt64 is comparable to Snowflake (#157)
$ cr spec/voice_spec_pr.cr
...
Finished in 15.64 milliseconds
3 examples, 0 failures, 0 errors, 0 pending
```
> Work on Bytes instead of IO::Memory in VoiceClient and VoiceUDP

- src/discordcr/rest.cr
This endpoint returns a 204 upon success, not the deleted role.
> Fix REST#delete_guild_role expecting a Role object response

- src/discordcr/client.cr
- src/discordcr/websocket.cr
This PR adds support for Discord's `zlib-stream` compression transport mode. (Ref #10 )
Initially I had a ton of difficulty with this because the stdlib's `Zlib::Reader` basically isn't meant to do this; It is really just meant to do one-shot inflation.
The first issue is that when you `Reader.new(io)`, it immediately tries to consume the zlib header from that IO. This isn't helpful for us because we basically need a single instance of a `Reader` to keep around forever, and having `@reader : Reader?` is annoying.
~~To fix this, I've subclassed `Zlib::Reader` into `Zlib::StreamReader` that lets us control when we read the header - *only* on the very first binary frame we receive, letting us keep a single instance around. I've made an instance method that calls `Zlib::Reader.read_header` as …
> Support zlib-stream gateway compression

- src/discordcr/client.cr
```
in lib/discordcr/src/discordcr/client.cr:118: 
instance variable '@client_id' of Discord::Client must be (UInt64 | Nil), not Discord::Snowflake
@client_id ||= get_oauth2_application.id
```
> Fix @client_id must be UInt64 not Snowflake

- src/discordcr/voice.cr
This uses the monotonic clock instead of the current time in `Discord.timed_run` which is more accurate since it's unaffected by time fluctuations such as leap seconds or manually changing the computer time.
> Use monotonic clock in Discord.timed_run

- src/discordcr/cache.cr
- src/discordcr/client.cr
Fixes DM channels not being cached
- Use ChannelType#dm? to check if we should cache a dm_channel
- Correct usage of Hash#fetch in resolve_dm_channel
> Fix DM channels from not being cached 

- src/discordcr/mappings/permissions.cr
- src/discordcr/rest.cr
This fixes a wrong permission in [`edit_channel_permissions`](https://meew0.github.io/discordcr/doc/master/Discord/REST.html#edit_channel_permissions(channel_id:UInt64|Snowflake,overwrite_id:UInt64|Snowflake,type:String,allow:Permissions,deny:Permissions)-instance-method)' docs and removes the comment in `Permissions.new` (see https://github.com/meew0/discordcr/pull/174#issuecomment-447901908).
It also adds 2 missing permissions to the `Permissions` enum.
> Fix edit_channel_permissions' docs and add missing permissions

- src/discordcr/client.cr
- src/discordcr/mappings/gateway.cr
- src/discordcr/rest.cr
Adds the new MESSAGE_REACTION_REMOVE_EMOJI gateway event as well as the new endpoint that comes with it.
> Add MESSAGE_REACTION_REMOVE_EMOJI event and endpoint
