src/discordcr/client.cr, src/discordcr/mappings/channel.cr, src/discordcr/mappings/gateway.cr, src/discordcr/mappings/voice.cr
No huge problems, but it would cause annoying messages to be printed to console every time.
=> Fix some wrong keys in mappings

src/discordcr/mappings/guild.cr
=> Fix the typing of GamePlaying#type

.gitignore, src/discordcr/mappings/channel.cr, src/discordcr/mappings/guild.cr, src/discordcr/mappings/permissions.cr, src/discordcr/mappings/user.cr, src/discordcr/rest.cr
Edit .gitignore to exclude .DS_Store files
For #34
=> Add permissions enum, add permissions value to Role

src/discordcr/mappings/channel.cr, src/discordcr/mappings/converters.cr, src/discordcr/rest.cr
I didn't bother with making any kind of embed builder to keep with the minimalist attitude. If necessary I can make one but why bother.
=> Add support for rich embeds

src/discordcr/client.cr
RX14 told me to do this
tested specs and formatted
=> wrap json parser in a builder for 0.20.5

src/discordcr/client.cr
Can be useful for stats, or for handling unsupported events.
=> Implement an event that runs on every dispatch

src/discordcr/client.cr, src/discordcr/mappings/gateway.cr
=> Update the client to use the new format of setting statuses

src/discordcr/client.cr
Previously automatic resuming didn't really work. These fixes make it work.
Thanks to Discord for having gateway problems right now so I could test this.
=> Fixes to resume logic

src/discordcr/dca.cr, src/discordcr/mappings/channel.cr, src/discordcr/mappings/gateway.cr, src/discordcr/mappings/guild.cr, src/discordcr/mappings/invite.cr, src/discordcr/mappings/user.cr, src/discordcr/mappings/voice.cr
=> Change nilable: true to Type? in fields

src/discordcr/mappings/gateway.cr, src/discordcr/mappings/guild.cr
Unfortunately, it seems like widget channel data is not sent in GUILD_CREATE.
=> Add missing Guild fields

src/discordcr/mappings/rest.cr, src/discordcr/rest.cr
* `REST#get_guild_vanity_url`
* `REST#modify_guild_vanity_url`
=> Adds REST methods for vanity URL

src/discordcr/client.cr
Fixes #72 and adds support for heartbeat ACKs. Should not be merged until long-running stability tests confirm the validity of these changes. If you can, please try these changes on your bot and confirm that they don't reduce stability.
=> Heartbeat fixes

src/discordcr/client.cr, src/discordcr/mappings/oauth2.cr, src/discordcr/rest.cr
=> Make @client_id optional, Oauth2Application mapping and REST

src/discordcr/mappings/channel.cr
https://discordapp.com/developers/docs/resources/channel#channel-object-channel-structure
=> Add missing Channel fields

src/discordcr/rest.cr
* `REST#get_guild_emojis`
* `REST#modify_guild_emoji`
* `REST#create_guild_emoji`
=> Adds REST methods for guild emojis

src/discordcr/client.cr
=> Fix typo in GUILD_EMOJIS_UPDATE

src/discordcr/client.cr, src/discordcr/mappings/gateway.cr, src/discordcr/mappings/rest.cr, src/discordcr/mappings/webhook.cr, src/discordcr/rest.cr
Add REST routes for webhooks
Add ModifyWebhookPayload and ExecuteWebhookPayload to handle nil
Create webhook struct mapping in separate file
Check for response on execute_webhook if wait is true
=> Implement Webhook resource

src/discordcr/client.cr
Provides additional information about exceptions to assist with debugging. I think this was brought up some time ago, but we didn't get around to it.
=> Log exceptions with Exception#inspect_with_backtrace

src/discordcr/client.cr
Calling `Discord::Client.new` always makes an outgoing HTTP request to `GET /gateway` to set up the internal `WebSocket`, which is not fun when you're trying to write specs for `Client` behavior without an internet connection, or don't really care to have your machine or CI spam Discord during development for no reason.
=> Lazily instantiate client websocket

src/discordcr/mappings/channel.cr
Adding activity as https://discordapp.com/developers/docs/resources/channel#message-object-message-activity-types
=> Add Message#activity

spec/discordcr_spec.cr, spec/snowflake_spec.cr, src/discordcr/cache.cr, src/discordcr/mappings/channel.cr, src/discordcr/mappings/converters.cr, src/discordcr/mappings/gateway.cr, src/discordcr/mappings/guild.cr, src/discordcr/mappings/invite.cr, src/discordcr/mappings/oauth2.cr, src/discordcr/mappings/rest.cr, src/discordcr/mappings/user.cr, src/discordcr/mappings/voice.cr, src/discordcr/mappings/webhook.cr, src/discordcr/rest.cr, src/discordcr/snowflake.cr, src/discordcr/voice.cr
Closes #106 
~~Still WIP, as the specs are failing as somehow the nanosecond is lost between `Time.epoch_ms` and `Time#epoch_ms`. I haven't dug into it to find out why / how to fix it: https://carc.in/#/r/3ych~~
Enough operators should be delegated to allow snowflakes to be sorted in a collection.
=> Implement Snowflake type

spec/discordcr_spec.cr, src/discordcr/client.cr, src/discordcr/websocket.cr
This _should_ make it so that gateway packet compression is handled correctly. Closes #10.
=> Support gateway packet compression

src/discordcr/mappings/channel.cr, src/discordcr/mappings/guild.cr, src/discordcr/mappings/user.cr
Adds `#mention` to `User`, `GuildMember`, `Channel`, `Role`, and `Emoji`
=> Add #mention methods to relevant types

src/discordcr/voice.cr
Expands the `WebSocket#close` delegation to set a heartbeat-sending flag, similar to what we do in `Client`.
Fixes #93
=> Exit voice heartbeat loop eventually after closing VWS

spec/cdn_spec.cr, spec/snowflake_spec.cr, src/discordcr/rest.cr, src/discordcr/snowflake.cr
~~Wait for crystal 0.27.0 to merge~~
Since crystal 0.27.0 has been released, this can be merged now.
=> Implement renaming of Time#epoch to #to_unix

README.md
=> Fix link to docs in readme (wrong version)

spec/discordcr_spec.cr, src/discordcr/client.cr
Utility method for https://discordapp.com/developers/docs/topics/gateway#sharding-sharding-formula
=> Implement Discord.shard_id

README.md, src/discordcr/rest.cr
This replaces old urls with the new one
=> Replace meew0 -> discordcr
